### ISSUE TITLE
签名失败，提示错误代码70003

### ISSUE THREAD

**Issue by zhujinhu21** [tencentyun/tls-sig-api-v2-cs#3]
RtcError: SignalChannel setup failure: ('errorCode': 70003, 'errorMsg': verify sig failed with info: [The UserSig in use is illegal. Please regenerate UserSig through official API，
用https://console.cloud.tencent.com/trtc/usersigtool 控制台校验是通过的

**Comment by zhangkun-Jser** [comment]
找到原因了吗，我也碰到了

**Comment by weijunyi** [comment]
一般来说就是生成 UserSig 参数和校验的时候不一致导致的。
